env: "local" # local dev prod
storage_path: "user=postgres password=grosBerg22 dbname=wallet_db sslmode=disable" # Будет порт для постгреса
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "admin"